image: "ubuntu:bionic"

# variables:
#   VARIABLE_X: abc
#   VARIABLE_Y: def

stages:
  - compile
  # - publish

compile:
  stage: compile
  before_script:
    - sudo make dep
  script:
    - sudo ./build.sh
    - echo && nginx -v && nginx -V
    - echo "todo = publish to PPA repo"
  artifacts:
    paths:
      - packages/

# publish:
#   stage: publish
#   script:
#     - echo "todo = publish to PPA repo"
